model_list:
  # OpenAI Models
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-3-5-haiku
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

  # Google Gemini Models
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: os.environ/GOOGLE_API_KEY

  # Azure OpenAI (uncomment and configure if you have Azure OpenAI)
  # - model_name: azure-gpt-4
  #   litellm_params:
  #     model: azure/your-deployment-name
  #     api_base: os.environ/AZURE_API_BASE
  #     api_key: os.environ/AZURE_API_KEY
  #     api_version: "2023-07-01-preview"

  # AWS Bedrock (uncomment and configure if you have AWS Bedrock access)
  # - model_name: claude-bedrock
  #   litellm_params:
  #     model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
  #     aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
  #     aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  #     aws_region_name: os.environ/AWS_REGION_NAME

general_settings:
  master_key: sk-1234 # Change this to a secure key
  # Uncomment the following if you want to use a database for key management
  # database_url: "postgresql://user:password@localhost:5432/litellm_db"

# Optional: Configure logging and monitoring
litellm_settings:
  set_verbose: true
  # success_callback: ["langfuse"]  # Uncomment to enable logging to external services
