model_list:
  # OpenAI Models
  - model_name: gpt-5-mini
    litellm_params:
      model: gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4.1-2025-04-14
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4.1
    litellm_params:
      model: gpt-4.1-2025-04-14
      api_key: os.environ/OPENAI_API_KEY

  - model_name: o3-deep-research
    litellm_params:
      model: o3-deep-research-2025-06-26
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-opus-41
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-3-7-sonnet
    litellm_params:
      model: anthropic/claude-3-7-sonnet-latest
      api_key: os.environ/ANTHROPIC_API_KEY

  # Google Gemini Models
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GOOGLE_API_KEY

  # Azure OpenAI (uncomment and configure if you have Azure OpenAI)
  - model_name: uva-azure-gpt-5
    litellm_params:
      model: azure/uvaeng-gpt-5
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2024-12-01-preview"

  # AWS Bedrock (uncomment and configure if you have AWS Bedrock access)
  # - model_name: claude-bedrock
  #   litellm_params:
  #     model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
  #     aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
  #     aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  #     aws_region_name: os.environ/AWS_REGION_NAME

general_settings:
  master_key: sk-1234 # Change this to a secure key
  # Uncomment the following if you want to use a database for key management
  # database_url: "postgresql://user:password@localhost:5432/litellm_db"

# Optional: Configure logging and monitoring
litellm_settings:
  set_verbose: true
  # success_callback: ["langfuse"]  # Uncomment to enable logging to external services
